# front-end/word_generator.py
# =============================================================================
# WORD DOCUMENT GENERATION
# =============================================================================
# PURPOSE: Convert AI-generated text into formatted Word document
# LIBRARY: python-docx for .docx file creation

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml.shared import OxmlElement, qn
import io
import re
from datetime import datetime

def generate_policy_word_doc(policy_text, title="Policy Document"):
    """   
    Create downloadable Word document from policy text
    
    FORMATTING APPLIED:
    1. Title: Bold, 16pt, centered
    2. Headings: Bold, 14pt, numbered (1., 2., 3.)
    3. Subheadings: Bold, 12pt, numbered (1.1, 1.2)
    4. Body text: Normal, 11pt, justified
    5. Lists: Bulleted or numbered as appropriate
    
    PARSING LOGIC:
    - Detect headings by: "# " prefix or "1." numbering
    - Detect subheadings by: "## " prefix or "1.1" numbering
    - Detect lists by: "-" or "*" or "1)" prefix
    - Everything else treated as body paragraph
    
    WHY WORD FORMAT?:
    - Industry standard for policy documents
    - Users can edit further (not PDF locked)
    - Preserves formatting better than plain text
    - Easy to share internally (universal format)
    
    STYLING:
    - Uses built-in python-docx styles
    - Custom styles defined for consistency
    - Matches typical corporate document style
    
    DOWNLOAD MECHANISM:
    - File saved to temporary location
    - Streamlit st.download_button displays
    - User clicks to download
    - Temp file cleaned up after download
    
    ERROR HANDLING:
    - Malformed markdown handled gracefully
    - Falls back to plain text if parsing fails
    - Logs warnings for debugging
    """
    
    doc = Document()
    
    # Set up document styles
    setup_document_styles(doc)
    
    # Split text into lines and process
    lines = policy_text.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # Check if it's a main title (all caps, contains "POLICY")
        if line.isupper() and 'POLICY' in line:
            title_para = doc.add_paragraph()
            title_run = title_para.add_run(line)
            title_run.font.size = Pt(18)
            title_run.font.bold = True
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            doc.add_paragraph()  # Add space after title
            
        # Check if it's a version/date line
        elif 'v1.0' in line.lower() or 'version' in line.lower():
            version_para = doc.add_paragraph()
            version_run = version_para.add_run(line)
            version_run.font.size = Pt(12)
            version_run.font.italic = True
            version_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            doc.add_paragraph()  # Add space
            
        # Check if it's a section header
        elif (re.match(r'^\d+\.?\s+', line) or 
              any(section in line for section in [
                  "Purpose", "Scope", "Policy Principles", "Fertility", 
                  "Pregnancy", "Menstrual", "Menopause", "Gender-Affirming", 
                  "Access to", "Legal and Regulatory", "Employee Support", 
                  "Review", "References"
              ])):
            section_para = doc.add_paragraph()
            section_run = section_para.add_run(line)
            section_run.font.size = Pt(14)
            section_run.font.bold = True
            section_para.space_before = Pt(12)
            section_para.space_after = Pt(6)
            
        # Regular content paragraphs
        else:
            content_para = doc.add_paragraph(line)
            content_para.space_after = Pt(6)
    
    # Add footer with generation info
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_run = footer_para.add_run(f"Generated by Policy Pulse on {datetime.now().strftime('%B %d, %Y')}")
    footer_run.font.size = Pt(10)
    footer_run.font.italic = True
    footer_para.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    
    # Save to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

def setup_document_styles(doc):
    """Set up consistent document styles"""
    
    # Set default font for the document
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)
    
    # Set margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)