[server]
fileWatcherType = "watchdog"
folderWatchBlacklist = [
  ".venv",
  "**\\.venv\\**",
  ".venv\\**",
  "**/torch/**",
  "**\\torch\\**",
  ".venv/Lib/site-packages/torch",
  ".venv\\Lib\\site-packages\\torch"
]